name: CraftAPI
version: 1.0.0
description: Provides RESTful API for Minecraft Server.
website: https://github.com/automataevox/CraftAPI
author: AutomataEvoX
contributors:
  - AutomataEvoX
api-version: 1.21
softdepend:
  - Maintenance

main: com.automataevox.craftapi.CraftAPI

commands:
  webhooks:
    description: Command to manage the Webhooks.
    usage: /webhooks <command> [args]
    permission: craftapi.webhooks
    aliases:
      - wh

  mcapi:
    description: Main command for the MinecraftServerAPI.
    usage: /craftapi <command> [args]
    permission: craftapi
