name: CraftAPI
version: 2.0.0
description: Provides RESTful API and Websocket communication for Minecraft Server.
website: https://github.com/automataevox/CraftAPI
author: AutomataEvoX
fork: Shweit
contributors:
  - AutomataEvoX
api-version: 1.21
softdepend:
  - Maintenance

main: com.automataevox.craftapi.CraftAPI

commands:
  webhooks:
    description: Command to manage the Webhooks.
    usage: /webhooks <command> [args]
    permission: capi.webhooks
    aliases:
      - wh

  capi:
    description: Main command for the CraftAPI.
    usage: /craftapi <command> [args]
    permission: capi
    aliases:
      - capi
